
title: Assay It Quality
url: https://assay.it 
baseurl:
logo: /site-icon.png

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: UA-78986123-4

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap